name: Lint & Compile Test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "**"

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - ">=16.x <17.x"
        steps:
            - name: Checkout repository
              uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true

            - name: Install dependencies
              run: npm i

            - name: Run ESLint
              run: npm run lint

    compile:
        needs: lint
        name: Compile
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - ">=16.x <17.x"
        steps:
            - name: Checkout repository
              uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true

            - name: Install dependencies
              run: npm i

            - name: Run Compile
              run: npm run build && rm -rf dist
